version: '3.5'

services:
  cmicro-mr-web:
    container_name: cmicro-mr-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - "1100:80"
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - cmicro-mr-be
    networks:
      - cmicro-mr-network

  cmicro-mr-be:
    container_name: cmicro-mr-be
    build:
      context: ./docker/php
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    ###> XDEBUG 3 ###
    # Use your client IP here
    # Linux: run "ip a | grep docker0"
    # Windows (with WSL2) and Mac: host.docker.internal
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=cmicro-mr-be
    ports:
      - '1000:8000'
    networks:
      - cmicro-mr-network
    depends_on:
      - cmicro-mr-postgres

  cmicro-mr-postgres:
    container_name: cmicro-mr-postgres
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: postgres_symfony
    volumes:
      - cmicro-mr-pgsql-data:/var/lib/postgresql/data
    networks:
      - cmicro-mr-network

  cmicro-mr-mysql:
    container_name: cmicro-mr-mysql
    image: mysql:8.0.26
    ports:
      - '3336:3306'
    environment:
      MYSQL_DATABASE: mysql_symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - cmicro-mr-mysql-data:/var/lib/mysql
    networks:
      - cmicro-mr-network
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  cmicro-mr-rabbit:
    container_name: cmicro-mr-rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - cmicro-mr-network

  cmicro-mr-mailer:
    container_name: cmicro-mr-mailer
    image: schickling/mailcatcher
    ports:
      - '1025:1025'
      - '1080:1080'
    networks:
      - cmicro-mr-network

networks:
  cmicro-mr-network:

volumes:
  cmicro-mr-pgsql-data:
  cmicro-mr-mysql-data:

