health_check:
  path: /api/v1/health-check
  controller: App\Controller\HealthCheckController
  methods: [GET]

messenger:
  path: /messenger
  controller: App\Controller\MessengerAction
  methods: [GET]

# User
api_activate_user:
  path: /api/v1/users/activate
  controller: App\Controller\User\ActivateUserAction
  methods: [PUT]

api_create_user:
  path: /api/v1/users/create
  controller: App\Controller\User\CreateUserAction
  methods: [POST]

api_login_check:
  path: /api/v1/users/login_check
  methods: [POST]

api_request_reset_password:
  path: /api/v1/users/request_reset_password
  controller: App\Controller\User\RequestResetPasswordAction
  methods: [POST]

api_resend_activation_email:
  path: /api/v1/users/resend_activation_email
  controller: App\Controller\User\ResendActivationEmailAction
  methods: [POST]

api_change_password:
  path: /api/v1/users/{id}/change_password
  controller: App\Controller\User\ChangePasswordAction
  methods: [PUT]

api_user_get:
  path: /api/v1/users/{id}
  controller: App\Controller\User\GetUserByIdAction
  methods: [GET]

api_update_user:
  path: /api/v1/users/{id}
  controller: App\Controller\User\UpdateUserAction
  methods: [PUT]

api_user_delete:
  path: /api/v1/users/{id}
  controller: App\Controller\User\DeleteUserAction
  methods: [DELETE]

api_user_get_all:
  path: /api/v1/users
  controller: App\Controller\User\GetUsersAction
  methods: [GET]


# Client
#api_activate_user:
#  path: /api/v1/users/activate
#  controller: App\Controller\User\ActivateUserAction
#  methods: [PUT]

api_client_create_user:
  path: /api/v1/clients/create_user
  controller: App\Controller\Client\CreateUserByClientAction
  methods: [POST]

api_client_create:
  path: /api/v1/clients/create
  controller: App\Controller\Client\CreateClientAction
  methods: [POST]

api_client_update:
  path: /api/v1/clients/{id}
  controller: App\Controller\Client\UpdateClientAction
  methods: [PUT]

